### PR TITLE
Handle double-connect on internal listener more gracefully

### PR DESCRIPTION
**Pull request by startuppartnerabhishek**

### CODE REVIEW

**Comment by startuppartnerabhishek** [comment]
Please note that these changes are COMPLETELY UNTESTED.

**Comment by bcwaldon** [comment]
@startuppartnerabhishek Do you need any testing support on this before merge?

**Review by deepaktawri — APPROVED** [review]

**Review by deepaktawri — APPROVED** [review]

**Comment by startuppartnerabhishek** [comment]
> @startuppartnerabhishek Do you need any testing support on this before merge?

I have requested @rahulbhivare to test this on my behalf and let me know of any problems.
cc: @omkar-sp 

Please note that my tests in lib/proxy/proxy-agent/tests appear to be broken, because I was not able to follow the instructions in  lib/proxy/proxy-agent/README to get off the ground with my unit tests. The unit-tests often provide a handy way to reproduce problems in a sandbox. This is not urgent, but would be helpful if we could resurrect it.

**Comment by startuppartnerabhishek** [comment]
> Should we add link to the MD formatted document ?

Sorry: I did not understand which document you mean here. Can you please elaborate?

**Review by rahulbhivare — APPROVED** [review]

**Pull request merged**
