### PR TITLE
Added support to run docker as user defined rahul

### PR DESCRIPTION
**Pull request by rahulbhivare**

### CODE REVIEW

**Comment by bcwaldon** [comment]
Hi @rahulbhivare - I don't think we need to add this. With docker, you just pass the `--user` flag with `docker run` command. We should rely on the client to properly execute docker and manage local filesystems instead of making changes to Dockerfiles like this.

**Comment by rahulbhivare** [comment]
> Hi @rahulbhivare - I don't think we need to add this. With docker, you just pass the `--user` flag with `docker run` command. We should rely on the client to properly execute docker and manage local filesystems instead of making changes to Dockerfiles like this.

Hi @bcwaldon  - Payload Controller launches docker container and it does not know what user payload-vendor wanted to run it as. It is up to payload vendors what other users they want to add in their own container environment.

**Comment by rolandjitsu** [comment]
This may actually be helpful for us. Our use case requires a specific user to run some cmds (right now we're getting around it by creating the user but not using the `USER` directive).

**Comment by rahulbhivare** [comment]
Closing PR, as the requirement is not valid at this stage.

**Pull request closed without merging**
